### ISSUE TITLE
File Upload Access Denied Error - Rev 2.2.8

### ISSUE THREAD

**Issue by smg6511** [ackwa/ImportUsersX#6]
New security enhancements in modx cause CSV uploads to fail ... maybe due to the use of an ajax iframe in the upload process. The response upon choosing a file is:

You don't have permission to access /core/components/importusersx/controllers/home.class.php
on this server.

The problem does not occur on 2.2.6.

**Comment by ghost** [comment]
This error is due to hard-coded paths and URLs in the assets/components/importusersx/mgr/widgets/home.panel.js file. There are at least two hard-coded URLs in that file alone. If the user sets up .htaccess rules to deny access to the core directory, or renames or moves the core directory, the file upload will fail, since the "core" directory is no longer accessible. The top-level directories (assets, connectors, core, manager) should always be set using MODx constants or variables, or set in settings. They should never be hard-coded.

**Comment by krismas** [comment]
You're right Susan, this code needs to be cleaned ;) I'll do it as soon as possible...

**Comment by vierkantemeter** [comment]
Pitty this is still not fixed.. I've tried to fix it, but ExtJS is beyond my knowledge.

Here's a quick fix if you just like me not want to disable your core/.htaccess file all the time. Add a line with `Allow from <your IP>`. This way only you have access.

```
IndexIgnore */*
<Files *.php>
Order Deny,Allow
Deny from all
Allow from 10.200.201.11
</Files>
```

**Comment by smg6511** [comment]
Closing as this is quite old and will be completely irrelevant for 3.x and beyond.
